services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "false"
      network.host: 0.0.0.0
    ports:
      - "9200:9200"
    cpus: 2
    mem_limit: 2g
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: always
  postgres:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: nexa
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d nexa" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack:latest
    ports:
      - '6379'
      - '8001'
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  s3:
    image: localstack/localstack:2.3
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: ap-southeast-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./s3/init:/etc/localstack/init/ready.d
    cpus: 0.5
    cpu_count: 3
    mem_limit: 500m

  #  es-init:
  #    build:
  #      context: ./es
  #    depends_on:
  #      elasticsearch:
  #        condition: service_healthy
  ollama:
    image: ollama/ollama:0.6.2
    ports:
      - "11434:11434"
    volumes:
      - /opt/.ollama:/root/.ollama
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  redis-data:
  postgres-data:
  elasticsearch-data: