services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      network.host: 0.0.0.0
      cluster.routing.allocation.disk.watermark.low: "98%"
      cluster.routing.allocation.disk.watermark.high: "99%"
      cluster.routing.allocation.disk.watermark.flood_stage: "99.5%"
    ports:
      - "9200:9200"
    cpus: 4
    mem_limit: 4g
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: always
  postgres:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: nexa
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d nexa" ]
      interval: 10s
      timeout: 5s
      retries: 5

  #  redis:
  #    image: redis/redis-stack:latest
  #    ports:
  #      - '6379:6379'
  #      - '8001:8001'
  #    healthcheck:
  #      test: [ "CMD", "redis-cli", "ping" ]
  #      interval: 5s
  #      timeout: 3s
  #      retries: 20
  #      start_period: 5s

  s3:
    image: minio/minio:RELEASE.2023-09-04T19-57-37Z
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: decadedecade
      MINIO_ROOT_PASSWORD: decadedecade
      MINIO_API_CORS_ALLOW_ORIGIN: "http://localhost:4200"
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5

  s3-init:
    image: minio/mc
    depends_on:
      s3:
        condition: service_healthy
    volumes:
      - ./compose/s3/init-minio.sh:/init-minio.sh
    entrypoint: /bin/sh /init-minio.sh

  #  ollama:
  #    image: ollama/ollama:0.6.6
  #    ports:
  #      - "11434:11434"
  #    volumes:
  #      - /opt/.ollama:/root/.ollama
  #    healthcheck:
  #      test: [ "CMD", "ollama", "list" ]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 5
  prometheus:
    image: prom/prometheus:v2.51.0
    ports:
      - "9090:9090"
    volumes:
      - ./compose/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cpus: 0.5
    cpu_count: 2
    mem_limit: 1g
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
  tempo:
    image: grafana/tempo:2.5.0
    command: -config.file=/etc/tempo.yaml
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./compose/tempo.yml:/etc/tempo.yaml

  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    mem_limit: 800m
    cpu_count: 1
    depends_on:
      - prometheus
      - loki
      - tempo
  faq:
    build:
      tags:
        - teri1712/faq_sidecar:latest
      context: ./faq
    ports:
      - "8000:8000"
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: nexa
      NUM_CLUSTERS: 3
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  graphrag-sidecar:
    build:
      tags:
        - teri1712/sidecar-graphrag:latest
      context: graph_rag
    ports:
      - "8002:8000"
    volumes:
      - ./graph_rag/input:/app/input
      - ./graph_rag/prompts:/app/prompts
      - ./graph_rag/config:/app/config
    environment:
      - GRAPHRAG_API_BASE=https://api.shopaikey.com/v1
      - GRAPHRAG_API_KEY=${ULTIMATE_API_KEY}
      - GRAPHRAG_ROOT=/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
