spring:
  docker:
    compose:
      enabled: false

  testcontainers:
    beans:
      startup: parallel

logging:
  level:
    root: INFO
aws:
  s3:
    access:
      id: test
      secret: test
management:
  tracing:
    enabled: true
  prometheus:
    metrics:
      export:
        enabled: false
  simple:
    metrics:
      export:
        enabled: true

frontend:
  host:
    address: http://localhost:4200