spring:
  ai:
    google:
      genai:
        embedding:
          text:
            options:
              model: gemini-embedding-001
              dimensions: 768
          project-id: ${GEMINI_PROJECT_ID}
          api-key: ${GEMINI_API_KEY}

        project-id: ${GEMINI_PROJECT_ID}
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite-preview
    model:
      chat: google-genai
      embedding:
        text: google-genai
