spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_only

  autoconfigure:
    exclude: org.springframework.ai.vectorstore.elasticsearch.autoconfigure.ElasticsearchVectorStoreAutoConfiguration