spring:
  ai:
    model:

      chat: ollama
      embedding: ollama
      audio:
        transcription: ollama
        speech: ollama
      image: ollama
      moderation: ollama
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
      chat:
        model: qwen3:0.6b
        options:
          temperature: 0.5
      embedding:
        model: nomic-embed-text

