spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_only
  datasource:
    url: jdbc:postgresql://localhost:5432/nexa
    username: root
    password: root

  elasticsearch:
    uris: http://localhost:9200
loki:
  url: http://localhost:3100/loki/api/v1/push

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

jwt:
  duration: 30m
  refresh:
    duration: 7d

logging:
  level:
    root: INFO


aws:
  s3:
    bucket: decade-bucket
    access:
      id: decadedecade
      secret: decadedecade
    endpoint: http://localhost:9000


frontend:
  host:
    address: http://localhost:4200