spring:
  application:
    name: nexa
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/nexa
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 15
      connection-timeout: 30000
      minimum-idle: 5
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: jpa
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: true
        highlight_sql: true
        order_updates: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
      client-type: lettuce
    elasticsearch:
      repositories:
        enabled: true
  flyway:
    clean-disabled: false
    enabled: true

  elasticsearch:
    uris: http://localhost:9200
  ai:
    google:
      genai:
        embedding:
          text:
            options:
              model: gemini-embedding-001
              dimensions: 768
          project-id: ${GEMINI_PROJECT_ID}
          api-key: ${GEMINI_API_KEY}

        project-id: ${GEMINI_PROJECT_ID}
        api-key: ${GEMINI_API_KEY}
    vectorstore:
      elasticsearch:
        dimensions: 768
        index-name: nexa-documents
        initialize-schema: true
        similarity: cosine
        embedding-field-name: embedding

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    model:
      chat: google-genai
server:
  port: 8080

frontend:
  host:
    address: http://localhost:4200

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,env,bean,info,prometheus,modulith
  endpoint:
    health:
      probes:
        enabled: true
      show-details: ALWAYS
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
actuator:
  user:
    name: admin
    password: admin
    roles: OPS


jwt.secret: vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl

jwt:
  duration: 15m
  refresh:
    duration: 7d

super:
  admin:
    username: super_ultimate_supreme_admin
    password: vclvclvclvcl



aws:
  s3:
    region: ap-southeast-1
    bucket: decade-bucket
    access:
      id: decade
      secret: decade
    endpoint: http://localhost:4566
springdoc:
  override-with-generic-response: false

logging:
  level:
    root: INFO
    com.decade.nexa: DEBUG
