spring:
  ai:
    model:
      chat: ollama
      embedding:
        text: ollama
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
      chat:
        model: Qwen2:0.5b
        options:
          temperature: 0.5
      embedding:
        model: nomic-embed-text

