apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sidecar-pvc
spec:
  accessModes:
    - {{ .Values.sidecar.persistence.accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{.Values.sidecar.persistence.storage}}